import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Box, Flex, Progress } from '@chakra-ui/react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<Box textAlign="center" mt={4} fontSize={32}>
					タイトル
				</Box>
				<Box
					as="span"

					// bgGradient="linear(to-r, green.200, pink.500)"
				>
					<Progress
						bgClip={''}
						max={10}
						value={5}
						mt={8}
						mx={20}
						borderRadius={10}
						size="lg"
						colorScheme="green"
						bgColor={'#E5EFE7'}
						sx={{
							'& > div': {
								background:
									'linear-gradient(100deg, rgba(100,193,120) 10%, rgba(246,196,101) 50%,  rgba(254,108,61) 100%)',
							},
						}}
						// bgGradient="linear(to-r, green.400, orange.400)"
					/>
				</Box>
				<Flex gap={'164px'} ml={24} fontSize={'16px'}>
					<Flex textAlign="center" mt={4} fontSize={32}>
						1
					</Flex>{' '}
					<Flex textAlign="center" mt={4} fontSize={32}>
						2
					</Flex>
					<Flex textAlign="center" mt={4} fontSize={32}>
						3
					</Flex>{' '}
					<Flex textAlign="center" mt={4} fontSize={32}>
						4
					</Flex>{' '}
					<Flex textAlign="center" mt={4} fontSize={32}>
						5
					</Flex>{' '}
					<Flex textAlign="center" mt={4} fontSize={32}>
						6
					</Flex>{' '}
					<Flex textAlign="center" mt={4} fontSize={32}>
						7
					</Flex>{' '}
					<Flex textAlign="center" mt={4} fontSize={32}>
						8
					</Flex>{' '}
					<Flex textAlign="center" mt={4} fontSize={32}>
						9
					</Flex>{' '}
					<Flex textAlign="center" mt={4} fontSize={32}>
						10
					</Flex>
				</Flex>
			</main>
		</>
	)
}
